# Basic config
language: cpp
dist: xenial
sudo: required
branches:
  only:
    - master
    - development

# Common external dependencies.
before_install:
  # Install GSL
  # Easy for mac, difficult for linux
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      BUILD_DIR=$(mktemp -d)
      pushd $BUILD_DIR
      curl -sL "https://github.com/microsoft/GSL/archive/v2.0.0.tar.gz" | tar xzf -
      cd GSL-2.0.0
      sudo cp -r include/gsl /usr/local/include/gsl
      popd
      rm -rf $BUILD_DIR
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      brew install cpp-gsl
    fi

# Final environment configs.
install:
  - |
    if [ -n "${VERSION}" ]; then
      export CC="${CC}-${VERSION}"
      export CXX="${CXX}-${VERSION}"
    fi
  - ${CXX} --version

# Build matrix
matrix:
  include:
    - env: VERSION=6
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    - env: VERSION=7
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    - env: VERSION=8
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
    - env: VERSION=6.0
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - g++-7
    - env: VERSION=7
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
            - g++-7
    - os: osx
      compiler: clang
      osx_image: xcode9.4
    - os: osx
      compiler: clang
      osx_image: xcode10.1

# Build and run.
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
